steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/grafana-494005/report-generator-server:latest', '.']
images:
  - 'gcr.io/grafana-494005/report-generator-server:latest'
options:
  logging: 'CLOUD_LOGGING_ONLY'
